schema_version = "1.0.0"

id = "pbrAudio"
version = "0.2.1"
name = "pbrAudio Render"
tagline = "Physically Based Render and Synthesis Audio Suite"
maintainer = "Malcom3D <malcom3d.gpl@gmail.com>"
type = "add-on"

# # Optional: link to documentation, support, source files, etc
website = "https://pbraudio.org/"

# # Optional: tag list defined by Blender and server, see:
# # https://docs.blender.org/manual/en/dev/advanced/extensions/tags.html
# tags = ["Animation", "Sequencer"]
tags = ["Node", "Physics", "Render"]

blender_version_min = "4.5.2"
# # Optional: Blender version that the extension does not support, earlier versions are supported.
# # This can be omitted and defined later on the extensions platform if an issue is found.
# blender_version_max = "5.1.0"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
# https://docs.blender.org/manual/en/dev/advanced/extensions/licenses.html
license = [
  "SPDX:GPL-3.0-or-later",
]
# # Optional: required by some licenses.
# copyright = [
#   "2002-2024 Developer Name",
#   "1998 Company Name",
# ]

# # Optional: list of supported platforms. If omitted, the extension will be available in all operating systems.
# platforms = ["windows-x64", "macos-arm64", "linux-x64"]
# # Other supported platforms: "windows-arm64", "macos-x64"
platforms = ["linux-x64"]

# # Optional: bundle 3rd party Python modules.
# # https://docs.blender.org/manual/en/dev/advanced/extensions/python_wheels.html
# wheels = [
#   "./wheels/hexdump-3.3-py3-none-any.whl",
#   "./wheels/jsmin-3.0.1-py3-none-any.whl",
# ]
wheels = [
   "./downloads/numpy-2.3.3-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl",
   "./downloads/PyYAML-6.0.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
#   "./downloads/typing_extensions-4.15.0-py3-none-any.whl",
#   "./downloads/donfig-0.8.1.post1-py3-none-any.whl",
   "./downloads/packaging-25.0-py3-none-any.whl",
#   "./downloads/numcodecs-0.16.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
#   "./downloads/crc32c-2.7.1-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
#   "./downloads/zarr-3.1.2-py3-none-any.whl",
#   "./downloads/zarrs-0.2.0-cp311-abi3-manylinux_2_28_x86_64.whl",
#   "./downloads/rich-14.1.0-py3-none-any.whl",
   "./downloads/cffi-2.0.0-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl",
   "./downloads/soundfile-0.13.1-py2.py3-none-manylinux_2_28_x86_64.whl",
   "./downloads/llvmlite-0.45.0-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl",
   "./downloads/numba-0.62.1-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl",
   "./downloads/dask-2025.9.1-py3-none-any.whl",
   "./downloads/click-8.3.0-py3-none-any.whl",
   "./downloads/cloudpickle-3.1.1-py3-none-any.whl",
   "./downloads/fsspec-2025.9.0-py3-none-any.whl",
   "./downloads/toolz-1.0.0-py3-none-any.whl",
   "./downloads/importlib_metadata-8.7.0-py3-none-any.whl",
   "./downloads/zipp-3.23.0-py3-none-any.whl",
   "./downloads/partd-1.4.2-py3-none-any.whl",
   "./downloads/locket-1.0.0-py2.py3-none-any.whl",
#   "./downloads/pywavelets-1.9.0-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl",
   "./downloads/scipy-1.16.2-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl",
   "./downloads/distributed-2025.9.1-py3-none-any.whl",
   "./downloads/jinja2-3.1.6-py3-none-any.whl",
   "./downloads/msgpack-1.1.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
   "./downloads/psutil-7.1.0-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
   "./downloads/tornado-6.5.2-cp39-abi3-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
   "./downloads/urllib3-2.5.0-py3-none-any.whl",
   "./downloads/zict-3.0.0-py2.py3-none-any.whl",
   "./downloads/sortedcontainers-2.4.0-py2.py3-none-any.whl",
   "./downloads/tblib-3.1.0-py3-none-any.whl",
   "./downloads/markupsafe-3.0.3-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl",
   "./downloads/trimesh-4.8.3-py3-none-any.whl",
   "./downloads/fast_simplification-0.1.13-cp311-abi3-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl",
   "./downloads/resampy-0.4.3-py3-none-any.whl",
#   "./downloads/Pympler-1.1-py3-none-any.whl",
#   "./downloads/networkx-3.6-py3-none-any.whl",
   "./downloads/python_fcl-0.7.0.10-cp311-cp311-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl",
   "./downloads/rtree-1.4.1-py3-none-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl",
#   "./downloads/pillow-12.0.0-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl",
#   "./downloads/meshlib-3.0.9.196-py38.py39.py310.py311.py312.py313.py314-none-manylinux_2_28_x86_64.whl",
   "./wheels/embreex-4.4.0rc0-cp311-cp311-linux_x86_64.whl",
#   "./wheels/pytinybvh-1.2.1-cp311-cp311-linux_x86_64.whl",
   "./wheels/pbraudiorender-0.1.dev367+g77568d797-py3-none-any.whl",
]

# # Optional: add-ons can list which resources they will require:
# # * files (for access of any filesystem operations)
# # * network (for internet access)
# # * clipboard (to read and/or write the system clipboard)
# # * camera (to capture photos and videos)
# # * microphone (to capture audio)
# #
# # If using network, remember to also check `bpy.app.online_access`
# # https://docs.blender.org/manual/en/dev/advanced/extensions/addons.html#internet-access
# #
# # For each permission it is important to also specify the reason why it is required.
# # Keep this a single short sentence without a period (.) at the end.
# # For longer explanations use the documentation or detail page.
#
# [permissions]
# network = "Need to sync motion-capture data to server"
# files = "Import/export FBX from/to disk"
# clipboard = "Copy and paste bone transforms"
[permissions]
files = "Import/export files for cache from/to disk"

# # Optional: advanced build settings.
# # https://docs.blender.org/manual/en/dev/advanced/extensions/command_line_arguments.html#command-line-args-extension-build
# [build]
# # These are the default build excluded patterns.
# # You only need to edit them if you want different options.
# paths_exclude_pattern = [
#   "__pycache__/",
#   "/.git/",
#   "/*.zip",
# ]
[build]
paths_exclude_pattern = [
   "__pycache__/",
   "/.git/",
   "/scripts/",
   "/build/",
   "/build.sh"
]
